name: Call the GKE workflow
on:
  workflow_dispatch:
    inputs:
      condition:
        type: boolean
        default: true

jobs:
  uses: ksuderman/github-actions-test/.github/workflows/gke.yml
  with:
    condition: ${{ inputs.condition }}
