name: Caller
on:
  workflow_dispatch:
    inputs:
      condition:
        type: boolean
        default: true

jobs:
  thething:
    uses: ./.github/workflows/called.yml
    with:
      condition: ${{ inputs.condition }}
