name: Do something based on input variable
on:
  workflow_call:
    inputs:
      condition:
        type: boolean
        default: true
      schedule:
        type: string
        default: '22 6,18 0 0 0'
jobs:
  yes:
    if: inputs.condition
    runs-on: ubunut-latest
    steps:
      - name: Do something
        run: echo "Yes"

  no:
    if: inputs.condition == false
    runs-on: ubuntu-latest
    steps:
      - name: Do something else
        run: echo "No"

  always:
    runs-on: ubuntu-latest
    steps:
      - name: Check the schedule
        run: |
          if [[ "${{ input.schedule }}" = "22 6,18 0 0 0" ]] ; then
            echo "Scheduled"
          else:
            echo "Un-scheduled          
          fi
          echo "Done"
