name: Reject Docker build if version already deployed

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The name of the repository
        required: true
        default: ksuderman/galaxy-min
      tag:
        description: The tag (version) to check
        required: true
        default: 22.01

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Get Docker metadata
        run: |
          response=$(curl -s -X HEAD -w "%{http_code}" https://hub.docker.com/v2/repositories/${{ github.event.inputs.repository }}/tags/${{ github.event.inputs.tag }})
          echo $response
      - name: Do something useful here.
        run: echo "Doing something useful."


