name: Docker test

on:
  workflow_dispatch:
    inputs:
      repository:
        description: The name of the repository
        required: true
        default: ksuderman/galaxy-min
      tag:
        description: The tag (version) to check
        required: true
        default: 22.01

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Don't build and push to release_* images if the image already exists
        run: |
          code=$(/usr/bin/curl -s -w "%{http_code}" -o /dev/null https://hub.docker.com/v2/repositories/${{ github.event.inputs.repository }}/tags/${{ github.event.inputs.tag }})
          if [[ $code == 200 ]] ; then
            echo "Image exists. Skipping the Docker build.
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      # \IMAGE_TAG=${{ steps.branch.outputs.name }} -t galaxy/galaxy-min:${{ steps.branch.outputs.name }} -t quay.io/galaxyproject/galaxy-min:${{ steps.branch.outputs.name }} -f .k8s_ci.Dockerfile
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          dockerfile: .k8s_ci.Dockerfile
          tags: |
            galaxy/galaxy-min:${{ steps.branch.outputs.name }}
            quay.io/galaxyproject/galaxy-min:${{ steps.branch.outputs.name }}
          buildArgs: |
            GIT_COMMIT=$(git rev-parse HEAD)
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            IMAGE_TAG=${{ steps.branch.outputs.name }}
