name: Perform a release
on:
  pull_request_target:
    types: [closed]
    branches:
      - master
jobs:
  package:
    if: github.event.pull_request.merged == true
    name: Tag and Release
    runs-on: ubuntu-latest
    steps:
      - name: Require a label and version bump to package and release
        uses: mheap/github-action-required-labels@v2
        with:
          mode: minimum
          count: 1
          labels: "release"
      - uses: actions/checkout@v2
      - uses: ksuderman/github-action-tag-release@master
        env:
          GITHUB_TOKEN: ${{ github.token }}