name: Tag and Release
on:
  pull_request_target:
    types: [closed]
jobs:
  package:
    if: github.event.pull_request.merged == true
    name: Package and push
    runs-on: ubuntu-latest
    steps:
      - name: Require a label and version bump to package and release
        uses: mheap/github-action-required-labels@v2
        with:
          mode: minimum
          count: 1
          labels: "version, release, major, enhancement, feature, minor, patch, bug, values"
      - uses: actions/checkout@v2
        with:
           persist-credentials: false
      - name: tag and release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          version=$(cat Chart.yaml | awk '/^version:/ { print $2 }')
          git config user.email $(git --no-pager log --format=format:'%ae' -n 1)
          git config user.name $(git --no-pager log --format=format:'%an' -n 1)
          git tag -a $version -m "Automatic release of v$version"
          git push origin $version
          gh release create $version --generate-notes --draft
