name: Perform a release
on:
  pull_request_target:
    types: [closed]
    branches:
      - master
jobs:
  release:
    if: github.event.pull_request.merged == true
    name: Tag and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ksuderman/github-action-tag-release@release_v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          file: Chart.yaml
          parser: awk
