name: Bump version
on:
  pull_request_target:
    types: [closed]
  branches:
    - dev
jobs:
  package:
    if: github.event.pull_request.merged == true
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - name: Require a label and version bump to package and release
        uses: mheap/github-action-required-labels@v2
        with:
          mode: minimum
          count: 1
          labels: "major, minor, patch"
      - uses: actions/checkout@v2
      - uses: ksuderman/github-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          type: ${{ join(github.event.pull_request.label.*.name, ' ') }}
          command: awk
          file: Chart.yaml

